package com.aeropuerto.losprimos.losPrimos.modelo;
// Generated 8/10/2022 11:01:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * Aerolineas generated by hbm2java
 */
@Entity
@Table(name="aerolineas"
    ,schema="public"
)
@Builder
public class Aerolineas  implements java.io.Serializable {


     private int idAerolinea;
     private String nombre;
     private String usuarioCreacion;
     private String usuarioModifica;
     private Date fechaCreacion;
     private Date fechaModifica;
     private int idEstado;

    public Aerolineas() {
    }

	
    public Aerolineas(int idAerolinea, int idEstado) {
        this.idAerolinea = idAerolinea;
        this.idEstado = idEstado;
    }
    public Aerolineas(int idAerolinea, String nombre, String usuarioCreacion, String usuarioModifica, Date fechaCreacion, Date fechaModifica, int idEstado) {
       this.idAerolinea = idAerolinea;
       this.nombre = nombre;
       this.usuarioCreacion = usuarioCreacion;
       this.usuarioModifica = usuarioModifica;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifica = fechaModifica;
       this.idEstado = idEstado;
    }
   
     @Id 

    
    @Column(name="id_aerolinea", unique=true, nullable=false)
    public int getIdAerolinea() {
        return this.idAerolinea;
    }
    
    public void setIdAerolinea(int idAerolinea) {
        this.idAerolinea = idAerolinea;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="usuario_creacion", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=22)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }




}


