package com.aeropuerto.losprimos.losPrimos.modelo;
// Generated 9/10/2022 08:27:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asientos generated by hbm2java
 */
@Entity
@Table(name="asientos"
    ,schema="public"
)
public class Asientos  implements java.io.Serializable {


     private int idAsiento;
     private int idAvion;
     private int idEstado;
     private String usuarioCreacion;
     private String usuarioModifica;
     private Date fechaCreacion;
     private Date fechaModifica;

    public Asientos() {
    }

	
    public Asientos(int idAsiento, int idAvion, int idEstado) {
        this.idAsiento = idAsiento;
        this.idAvion = idAvion;
        this.idEstado = idEstado;
    }
    public Asientos(int idAsiento, int idAvion, int idEstado, String usuarioCreacion, String usuarioModifica, Date fechaCreacion, Date fechaModifica) {
       this.idAsiento = idAsiento;
       this.idAvion = idAvion;
       this.idEstado = idEstado;
       this.usuarioCreacion = usuarioCreacion;
       this.usuarioModifica = usuarioModifica;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifica = fechaModifica;
    }
   
     @Id 

    
    @Column(name="id_asiento", unique=true, nullable=false)
    public int getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(int idAsiento) {
        this.idAsiento = idAsiento;
    }

    
    @Column(name="id_avion", nullable=false)
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="usuario_creacion", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=22)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


