package com.aeropuerto.losprimos.losPrimos.modelo;
// Generated 8/10/2022 10:58:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * Boletos generated by hbm2java
 */
@Entity
@Table(name="boletos"
    ,schema="public"
)
@Builder
public class Boletos  implements java.io.Serializable {


     private int idBoleto;
     private String idCliente;
     private int idEstado;
     private int idVuelo;
     private Date fechaCreacion;
     private String usuarioCrecion;
     private Date fechaModifica;
     private String usuarioModifica;

    public Boletos() {
    }

	
    public Boletos(int idBoleto, String idCliente, int idEstado, int idVuelo) {
        this.idBoleto = idBoleto;
        this.idCliente = idCliente;
        this.idEstado = idEstado;
        this.idVuelo = idVuelo;
    }
    public Boletos(int idBoleto, String idCliente, int idEstado, int idVuelo, Date fechaCreacion, String usuarioCrecion, Date fechaModifica, String usuarioModifica) {
       this.idBoleto = idBoleto;
       this.idCliente = idCliente;
       this.idEstado = idEstado;
       this.idVuelo = idVuelo;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCrecion = usuarioCrecion;
       this.fechaModifica = fechaModifica;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_boleto", unique=true, nullable=false)
    public int getIdBoleto() {
        return this.idBoleto;
    }
    
    public void setIdBoleto(int idBoleto) {
        this.idBoleto = idBoleto;
    }

    
    @Column(name="id_cliente", nullable=false)
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="id_vuelo", nullable=false)
    public int getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(int idVuelo) {
        this.idVuelo = idVuelo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=22)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="usuario_crecion", length=50)
    public String getUsuarioCrecion() {
        return this.usuarioCrecion;
    }
    
    public void setUsuarioCrecion(String usuarioCrecion) {
        this.usuarioCrecion = usuarioCrecion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


