package com.aeropuerto.losprimos.losPrimos.modelo;
// Generated 8/10/2022 11:03:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * VueloClase generated by hbm2java
 */
@Entity
@Table(name="vuelo_clase"
    ,schema="public"
)
@Builder
public class VueloClase  implements java.io.Serializable {


     private VueloClaseId id;
     private int precio;
     private String usuarioCrea;
     private String usuarioModifica;
     private Date fechaCreacion;
     private Date fechaModifica;

    public VueloClase() {
    }

	
    public VueloClase(VueloClaseId id, int precio) {
        this.id = id;
        this.precio = precio;
    }
    public VueloClase(VueloClaseId id, int precio, String usuarioCrea, String usuarioModifica, Date fechaCreacion, Date fechaModifica) {
       this.id = id;
       this.precio = precio;
       this.usuarioCrea = usuarioCrea;
       this.usuarioModifica = usuarioModifica;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifica = fechaModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVuelo", column=@Column(name="id_vuelo", nullable=false) ), 
        @AttributeOverride(name="idClase", column=@Column(name="id_clase", nullable=false) ) } )
    public VueloClaseId getId() {
        return this.id;
    }
    
    public void setId(VueloClaseId id) {
        this.id = id;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }

    
    @Column(name="usuario_crea", length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=22)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


